---
# - name: check current motd
#   command: diff -s /etc/motd /etc/update-motd.d/00-header
#   register: diff_output
#   changed_when: "diff_output.rc == 1"
#   failed_when: False

- name: create directory
  file:
    path: /etc/update-motd.d
    state: directory

- name: copy config files
  template:
    src: 00-header.j2
    dest: /etc/update-motd.d/00-header
    mode: 0755
  notify: update motd
